theme: jekyll-theme-minimal
title: John Cherian
description: Scientific Associate at D.E. Shaw Research
baseurl: "" 
url: ""
twitterusername: jjcherian
github_username: jjcherian

plugins:
  - jekyll-feed
